const data = {
  products: [
    {
      name: 'eru',
      slug: 'eru',
      category: 'Foods',
      image: '/images/eru.jpg',
      price: 5,
      countInStock: 50,
      origin: 'Cameroon',
      description: 'fresh vegetable',
      rating: 4.5,
    },
    {
      name: 'necklace',
      slug: 'necklace',
      category: 'Accessories',
      image: '/images/chaine1.jpg',
      price: 15,
      countInStock: 25,
      origin: 'Cameroon',
      description: '',
      rating: 4.5,
    },
    {
      name: 'sandal',
      slug: 'sandal',
      category: 'Shoes',
      image: '/images/sandal1.jpg',
      price: 25,
      countInStock: 50,
      origin: 'Cameroon',
      description: 'high quality',
      rating: 4.5,
    },
    {
      name: 'shirt',
      slug: 'shirt',
      category: 'Clothes',
      image: '/images/gang1.jpg',
      price: 10,
      countInStock: 50,
      origin: 'Cameroon',
      description: 'high quality',
      rating: 4.5,
    },
  ],
};
export default data;
